
import { config } from 'dotenv';
config();

import '@/ai/flows/mentor-bot-assistance.ts';
import '@/ai/flows/personalized-tutorial-creation.ts';
import '@/ai/flows/chatbot-guidance.ts';
import '@/ai/flows/submit-feedback.ts';
import '@/ai/flows/evaluate-tutorial-answers.ts';
import '@/ai/flows/save-tutorial-answers.ts';
import '@/ai/flows/get-tutorial-answers.ts';
import '@/ai/flows/create-tribe.ts';
import '@/ai/flows/get-tribes.ts';
import '@/ai/flows/join-tribe.ts';
import '@/ai/flows/get-tutorial-feedback.ts';
import '@/ai/flows/delete-tribe.ts';
import '@/ai/flows/update-tribe-meetings.ts';
import '@/ai/flows/manage-applications.ts';
import '@/ai/flows/user-profile.ts';
import '@/ai/flows/get-feedback.ts';
import '@/ai/flows/get-chat-sessions.ts';
import '@/ai/flows/get-users.ts';
import '@/ai/flows/get-all-tutorial-answers.ts';
import '@/ai/flows/get-tribe-members.ts';
import '@/ai/flows/submit-meeting-report.ts';
import '@/ai/flows/get-meeting-reports.ts';
import '@/ai/flows/send-test-email.ts';
import '@/ai/flows/normalize-phone-numbers.ts';
import '@/ai/flows/update-user-level.ts';
import '@/ai/flows/delete-user.ts';
import '@/ai/flows/send-diploma-email.ts';
